// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGargamelPatternForMatrixOcx wrapper class

class CGargamelPatternForMatrixOcx : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGargamelPatternForMatrixOcx)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x941c461f, 0x8ba3, 0x406a, { 0xb0, 0x9b, 0x98, 0xd4, 0xc3, 0x9f, 0xc5, 0x24 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetPatternForMatrixScript();
	void SetPatternForMatrixScript(LPCTSTR);

// Operations
public:
	void AboutBox();
};
