#if !defined(AFX_GARGAMELSPLIT_H__CC88F180_43EB_11D5_9E85_0000E8C3064A__INCLUDED_)
#define AFX_GARGAMELSPLIT_H__CC88F180_43EB_11D5_9E85_0000E8C3064A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGargamelSplitOcx wrapper class

class CGargamelSplitOcx : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGargamelSplitOcx)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x3731efa6, 0xf83d, 0x11d4, { 0x9e, 0x85, 0x0, 0x0, 0xe8, 0xc3, 0x6, 0x4a } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetSplitScript();
	void SetSplitScript(LPCTSTR);

// Operations
public:
	void NotifyFlagrantDialogOk();
	void NotifyFlagrantDialogCancel();
	void SetDirectory(LPCTSTR qPath);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GARGAMELSPLIT_H__CC88F180_43EB_11D5_9E85_0000E8C3064A__INCLUDED_)
