// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "grapherrenovatordialog.h"

/////////////////////////////////////////////////////////////////////////////
// CGrapherRenovatorDialog

IMPLEMENT_DYNCREATE(CGrapherRenovatorDialog, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGrapherRenovatorDialog properties

/////////////////////////////////////////////////////////////////////////////
// CGrapherRenovatorDialog operations

long CGrapherRenovatorDialog::DoModal()
{
	long result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
