#if !defined(AFX_GRAPHERRENOVATORDIALOG_H__C0148DA0_4653_11D5_9E85_0000E8C3064A__INCLUDED_)
#define AFX_GRAPHERRENOVATORDIALOG_H__C0148DA0_4653_11D5_9E85_0000E8C3064A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGrapherRenovatorDialog wrapper class

class CGrapherRenovatorDialog : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGrapherRenovatorDialog)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x9ff3ac45, 0x4612, 0x11d5, { 0x9e, 0x85, 0x0, 0x0, 0xe8, 0xc3, 0x6, 0x4a } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long DoModal();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GRAPHERRENOVATORDIALOG_H__C0148DA0_4653_11D5_9E85_0000E8C3064A__INCLUDED_)
