//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Grapher.rc
//
#define ID_GRPLOTWIZARD_DRAW            2
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GRAPHER                     129
#define IDR_CHILDFRAME                  130
#define IDR_GRSCRIPTER                  131
#define IDD_GR_PLOT_MIXER               131
#define IDB_OPTIONTREECTRL_CHECKOFF     131
#define IDB_OPTIONTREECTRL_RADIOON      132
#define IDB_OPTIONTREECTRL_CHECKON      133
#define IDB_OPTIONTREECTRL_ITEMS        134
#define IDB_EXEC_GR                     135
#define IDB_OPTIONTREECTRL_RADIOOFF     137
#define IDD_GR_HISTORY                  137
#define IDC_ZOOM_IN_CURSOR              141
#define IDC_ZOOM_OUT_CURSOR             142
#define IDD_GR_LOG                      143
#define IDC_HAND_GRAPSED_CURSOR         143
#define IDC_HAND_SPREADED_CURSOR        144
#define IDD_GR_ATTR_PAGE                155
#define IDD_GR_AXIS_PAGE                156
#define IDD_GR_DATA_PAGE                157
#define IDD_GR_GLOB_PAGE                158
#define IDD_GR_SYMB_PAGE                159
#define IDD_GR_TEXT_PAGE                160
#define IDD_GR_UFUN_PAGE                161
#define IDD_GR_VIEW_PAGE                162
#define IDD_GR_PLOT_PAGE                163
#define IDD_GR_PLOT_SYMBOL_PORTFOLIO    164
#define IDD_GR_SMALL_FONT_SELECTION     168
#define IDD_GR_DEFAULT_SYMBOL           169
#define IDD_GR_PLOT_WIZARD              170
#define IDD_GR_PATH_ENVIRONMENT         172
#define IDD_GR_XYZB_PAGE                173
#define IDB_ARROW_LEFT                  176
#define IDB_ARROW_RIGHT                 177
#define IDB_GR_WIZARD                   178
#define IDB_GR_SCRIPT                   179
#define IDB_CLEAR                       180
#define IDB_FILE_OPEN                   181
#define IDB_GARGAMEL                    182
#define IDB_GR_LOG                      183
#define IDB_PREFERENCE                  185
#define IDB_PALLETE                     186
#define IDB_GR_PROPERTYSHEET            187
#define IDB_GR_MIXER                    188
#define IDB_GR_RENOVATOR                189
#define IDB_SMURFETTE                   191
#define ID_GRPLOTWIZARD_XSERIES         900
#define ID_GRPLOTWIZARD_XSCATTER        901
#define ID_GRPLOTWIZARD_MAP             902
#define ID_GRPLOTWIZARD_XSERIES01       903
#define ID_GRPLOTWIZARD_XSERIES02       904
#define ID_GRPLOTWIZARD_XSCATTER01      905
#define ID_GRPLOTWIZARD_XSCATTER02      906
#define ID_GRPLOTWIZARD_XSCATTER03      907
#define ID_GRPLOTWIZARD_XSCATTER04      908
#define ID_GRPLOTWIZARD_XSCATTER05      909
#define ID_GRPLOTWIZARD_XSCATTER06      910
#define ID_GRPLOTWIZARD_XSCATTER07      911
#define ID_GRPLOTWIZARD_MAP01           912
#define ID_GRPLOTWIZARD_MAP02           913
#define ID_GR_PLOT_MIXER_TREECTRL       1002
#define ID_RELAYOUT                     1004
#define ID_GRSLCT_LEGEND_SLIDER_TEXT    1006
#define ID_GRSLCT_LEGEND_SLIDER         1007
#define ID_GRPLOT_EMF_CANVAS            1008
#define ID_GRSLCT_LEGEND_TEXT_FONTATTR  1011
#define ID_GRSLCT_ETC_MAP_NO_FORMAT     1012
#define ID_GRSLCT_COLS_WIZARD           1013
#define ID_GRDATA_NAME                  1013
#define ID_GRHISTORY_EDIT               1017
#define ID_GRTEXT_LISTCTRL              1019
#define ID_GRVIEW_STEP                  1023
#define ID_GRPLOT_TREECTRL              1025
#define ID_GRSLCT_SYMBOL_LINE_WIDTH     1026
#define ID_GRVIEW_ROW                   1026
#define ID_GRSLCT_SYMBOL_LINE_WIDTH_SPIN 1027
#define ID_GRVIEW_COL                   1027
#define ID_GRAPHER_VERSION              1028
#define ID_GRVIEW_RCINDEX               1028
#define ID_BITMAP_GRIPPER               1029
#define ID_GRVIEW_RCLAPPLY              1029
#define ID_GRSLCT_MOMENT                1032
#define ID_GRSLCT_MAP                   1033
#define ID_GRAXIS_AXIS                  1034
#define ID_GRVIEW_MOVE_LEFT             1034
#define ID_GRAXIS_MAJORTICK             1035
#define ID_GRVIEW_MOVE_RIGHT            1035
#define ID_GRAXIS_MINORTICK             1036
#define ID_GRVIEW_MOVE_UP               1036
#define ID_GRAXIS_TICKLABEL             1037
#define ID_GRVIEW_MOVE_DOWN             1037
#define ID_GRAXIS_AXISTITLE             1038
#define ID_GRAXIS_MAJORGRID             1039
#define ID_GRAXIS_MINORGRID             1040
#define IDC_CHECK1                      1041
#define IDC_CHECK2                      1042
#define IDC_CHECK3                      1043
#define ID_GRAXIS_LABEL_FORMAT          1045
#define ID_GRSLCT_BATCHJOB              1047
#define ID_GRGLOB_HEADER_SPACEFACTOR_SPIN 1052
#define ID_GRDATA_FROMFILE_BLOCKINDEX   1054
#define ID_GRSYMB_DISPLAY_ON            1056
#define ID_GRSYMB_DISPLAY_OFF           1057
#define ID_GRXYZB_COLUMNS               1058
#define ID_GRXYZB_ADD                   1059
#define ID_GRXYZB_GROUPS                1060
#define ID_GRXYZB_XLB                   1061
#define ID_GRXYZB_YLB                   1062
#define ID_GRXYZB_ZLB                   1063
#define ID_GRXYZB_XUB                   1064
#define ID_GRXYZB_YUB                   1065
#define ID_GRXYZB_ZUB                   1066
#define ID_SCRIPT_DIALOG_CLEAR          1069
#define ID_SCRIPT_DIALOG_SAVEAS         1070
#define ID_GRAXIS_AXIS_DISPLAY          1071
#define ID_SCRIPT_DIALOG_PRINT          1071
#define ID_GRTEXT_TEXT01                1074
#define ID_GRTEXT_TEXT02                1077
#define ID_GRAXIS_TICKMAJOR_DISPLAY     1077
#define ID_GRAXIS_LABEL_EQUATION        1078
#define ID_GRSLCT_YUB_AUTO              1078
#define ID_GRGLOB_OUTFILE_HPGL          1079
#define ID_GRAXIS_TITLE_SPACEFACTOR     1079
#define ID_GRTEXT_TEXT03                1080
#define ID_GRAXIS_TICKMAJOR_STEP        1080
#define ID_GRGLOB_HEADER_SPACEFACTOR    1080
#define ID_GRAXIS_TICKMAJOR_STEP_AUTO   1081
#define ID_GRXYZB_VARIABLES             1081
#define ID_GRAXIS_LABEL_DISPLAY         1082
#define ID_GRXYZB_BOUNDARY              1082
#define ID_GRUFUN_LIST                  1083
#define ID_GRSLCT_LEGEND_TEXT           1083
#define ID_GRAXIS_TICKMINOR_STEP        1083
#define ID_GRSLCT_LEGEND_SIZE           1084
#define ID_GRAXIS_TITLE_STRING          1084
#define ID_GRSLCT_SYMBOL_SIZE           1085
#define ID_GRAXIS_TITLE_DISPLAY         1085
#define ID_GRTEXT_TEXT04                1086
#define ID_GRSLCT_ETC_MAP_COLOR_TOTAL   1086
#define ID_GRAXIS_GRIDMAJOR_DISPLAY     1086
#define ID_GRSLCT_LEGEND_Y              1087
#define ID_GRAXIS_GRIDMINOR_DISPLAY     1087
#define ID_GRSLCT_SYMBOL_NCOPY          1088
#define ID_GRAXIS_TICKMINOR_DISPLAY     1088
#define ID_GRAXIS_TICKMAJOR_INSIDE      1089
#define ID_GRAXIS_TICKMINOR_INSIDE      1090
#define ID_GRGLOB_OUTFILE_ATTRIBUTE     1091
#define ID_GRDATA_FROMPREVIOUSMATRIX    1091
#define ID_GRSLCT_ETC_MOMENT_RANGE      1091
#define ID_GRAXIS_TICKMAJOR_OUTSIDE     1091
#define ID_GRVIEW_X1                    1092
#define ID_GRDATA_FROMPREVIOUSCLONEMATRIX 1092
#define ID_GRAXIS_TICKMINOR_OUTSIDE     1092
#define ID_GRVIEW_Y1                    1093
#define ID_GRATTR_SCALE_Y_LOGARITHMIC   1093
#define ID_GRAXIS_AXLETHICKNESS         1093
#define ID_GRVIEW_X2                    1094
#define ID_GRATTR_SCALE_Z_LOGARITHMIC   1094
#define ID_GRVIEW_Y2                    1095
#define ID_GRDATA_FROMSCRIPT            1096
#define ID_GRATTR_SCALE_Z_NORMAL        1097
#define ID_GRATTR_SCALE_X_SERIES        1098
#define ID_GRAXIS_TICKMINOR_STEP_AUTO   1100
#define ID_GRATTR_TYPE_GENETIC          1101
#define ID_GRAXIS_GRIDMINOR_COLOR       1101
#define ID_GRATTR_TYPE_MOMENT           1102
#define ID_GRAXIS_GRIDMAJOR_COLOR       1102
#define ID_GRAXIS_TITLE_COLOR           1103
#define ID_GRATTR_TYPE_AREA             1103
#define ID_GRATTR_TYPE_BAR              1104
#define ID_GRATTR_TYPE_COLUMN           1105
#define ID_GRAXIS_LABEL_COLOR           1105
#define ID_GRTEXT_TEXT01_BTN            1106
#define ID_GRATTR_TYPE_PIE              1106
#define ID_GRTEXT_TEXT02_BTN            1107
#define ID_GRAXIS_COLOR                 1107
#define ID_GRATTR_SCALE_X_WEIBULL       1107
#define ID_GRTEXT_TEXT03_BTN            1108
#define ID_GRATTR_SCALE_Y_WEIBULL       1108
#define ID_GRTEXT_TEXT04_BTN            1109
#define ID_GRATTR_SCALE_Z_WEIBULL       1109
#define ID_GRAXIS_LABEL_FONTATTR        1109
#define ID_GRAXIS_TITLE_FONTATTR        1110
#define ID_GRATTR_TYPE_FLAT3D           1110
#define ID_GRSLCT_SYMBOL_PEN_SPIN       1110
#define ID_GRTEXT_LISTCTRL_ADD          1110
#define ID_GRATTR_DIM_2D                1111
#define ID_GRTEXT_LISTCTRL_DELETE       1111
#define ID_GRATTR_DIM_3D                1112
#define ID_GRTEXT_LISTCTRL_BTN          1112
#define ID_GRATTR_TYPE_GENETICPLUS      1113
#define ID_GRAXIS_ID                    1117
#define ID_GRAXIS_LOC_LOWBOUNDARY       1119
#define ID_GRAXIS_TYPE_X                1120
#define ID_GRAXIS_TYPE_Y                1121
#define ID_GRAXIS_GRIDMAJOR_LINESTYLE   1122
#define ID_GRAXIS_GRIDMINOR_LINESTYLE   1124
#define ID_GRAXIS_LOC_MIDDLE            1126
#define ID_GRAXIS_LOC_HIGHBOUNDARY      1127
#define ID_GRAXIS_LINESTYLE             1128
#define ID_GRAXIS_LOC_ANY               1130
#define ID_GRAXIS_LOC_ANY_FROM          1131
#define ID_GRAXIS_LOC_ANY_TO            1132
#define ID_GRAXIS_LOC_ANY_AT            1133
#define ID_GRGLOB_XSCALE                1136
#define ID_GRGLOB_YSCALE                1137
#define ID_GRGLOB_XTRANSLATE            1138
#define ID_GRGLOB_YTRANSLATE            1139
#define ID_GRGLOB_ROTATION              1140
#define ID_GRGLOB_LANDSCAPE             1141
#define ID_GRGLOB_PORTRAIT              1142
#define ID_GRGLOB_HEADER                1143
#define ID_GRGLOB_HEADER_ATTRIBUTE      1144
#define ID_GRGLOB_OUTFILE               1145
#define ID_GRGLOB_OUTFILE_PS            1146
#define ID_GRGLOB_OUTFILE_GPS           1147
#define ID_GRGLOB_OUTFILE_EPS           1148
#define ID_GRATTR_PREVIOUS              1149
#define ID_GRGLOB_LOG_ECHOPLOTPOINTS    1149
#define ID_GRATTR_SCALE_X_LINEAR        1150
#define ID_GRATTR_SCALE_Y_LINEAR        1151
#define ID_GRATTR_SCALE_Z_LINEAR        1152
#define ID_GRATTR_SCALE_X_LOGARITHMIC   1153
#define ID_GRATTR_SCALE_X_NORMAL        1154
#define ID_GRATTR_SCALE_Y_NORMAL        1155
#define ID_GRDATA_FROMFILE              1156
#define ID_GRDATA_FROMUSERFUNCTION      1158
#define ID_GRDATA_FROMSCRIPT_PATTERN    1160
#define ID_GRDATA_FROMSCRIPT_SPLIT      1161
#define ID_GRDATA_FROMSCRIPT_PATTERN_BROWSER 1162
#define ID_GRDATA_GRXYFILE              1163
#define ID_GRDATA_FILE_BROWSER          1164
#define ID_GRDATA_EXCHANGEROWCOLUMN     1165
#define ID_GRDATA_FROMSCRIPT_SPLIT_BROWSER 1166
#define ID_GRDATA_FROMSCRIPT_OPTION     1167
#define ID_GRDATA_REUSEFILEONADISK      1168
#define ID_GRDATA_GRXYFILE_BROWSER      1169
#define ID_GRDATA_FILE_VIEWER           1170
#define ID_GRDATA_FILE_VIEWER2          1171
#define ID_GRDATA_FILE_DBIVIEWER        1171
#define ID_GRDATA_GRFOLDER              1172
#define ID_GRDATA_SORTBYXCOLUMN         1173
#define ID_GRSLCT_XLB                   1174
#define ID_GRDATA_FILE_APPLYALL         1174
#define ID_GRSLCT_XLB_AUTO              1175
#define ID_GRSLCT_XUB                   1176
#define ID_GRSLCT_XUB_AUTO              1177
#define ID_GRSLCT_YLB                   1178
#define ID_GRSLCT_YLB_AUTO              1179
#define ID_GRSLCT_YUB                   1180
#define ID_GRSLCT_ZLB                   1181
#define ID_GRSLCT_ZLB_AUTO              1182
#define ID_GRSLCT_ZUB                   1183
#define ID_GRSLCT_ZUB_AUTO              1184
#define ID_GRSLCT_SYMBOL_TYPE           1185
#define ID_GRXYZB_XLB_DATA              1185
#define ID_GRSLCT_SYMBOL_PEN            1186
#define ID_GRXYZB_XUB_DATA              1186
#define ID_GRXYZB_YLB_DATA              1187
#define ID_GRSLCT_LEGEND_X              1188
#define ID_GRXYZB_YUB_DATA              1188
#define ID_GRSLCT_XCOLS                 1189
#define ID_GRSLCT_YCOLS                 1190
#define ID_GRSLCT_ZCOLS                 1191
#define ID_GRSLCT_LEGEND_Y_AUTO         1192
#define ID_GRXYZB_ZLB_DATA              1192
#define ID_GRSLCT_ADD                   1193
#define ID_GRSLCT_DEL                   1194
#define ID_GRSLCT_PREV                  1195
#define ID_GRSLCT_NEXT                  1196
#define ID_GRSLCT_LEGEND_X_AUTO         1197
#define ID_GRXYZB_ZUB_DATA              1197
#define ID_GRSLCT_ADDALL                1198
#define ID_GRAXIS_ADD                   1199
#define ID_GRAXIS_DEL                   1200
#define ID_GRSLCT_SYMBOL_COLOR          1207
#define ID_GRSLCT_SYMBOL_LINE_COLOR     1208
#define ID_GRSLCT_ETC_MAP_COLOR_MIN     1209
#define ID_GRSLCT_ETC_MAP_COLOR_MAX     1210
#define ID_GRSLCT_SYMBOL_SOLID          1213
#define ID_GRSLCT_LINECONNECTION_CB     1214
#define ID_GRSLCT_SYMBOL_SIZE_SPIN      1215
#define ID_GRSLCT_LEGEND_SIZE_SPIN      1216
#define ID_GRSLCT_ETC_MOMENT_RANGE_SPIN 1217
#define ID_GRSLCT_LEGEND_CB             1218
#define ID_GRSLCT_SYMBOL_CB             1219
#define ID_GRSLCT_ETC_MAP_COLOR_TOTAL_SPIN 1220
#define ID_GRAXIS_TITLE_SPACEFACTOR_SPIN 1225
#define ID_GRAXIS_AXLETHICKNESS_SPIN    1226
#define ID_FONTD_COLOR                  1228
#define ID_FONTD_ANGLE                  1229
#define ID_FONTD_WIDTH                  1231
#define ID_FONTD_HEIGHT                 1232
#define ID_FONTD_ALIGNMENT              1233
#define ID_GRUFUN_TEXT                  1236
#define ID_GRUFUN_HELP                  1237
#define ID_GRUFUN_CLEAR                 1238
#define ID_GRUFUN_TRY                   1239
#define ID_GRLOG_EDIT                   1239
#define ID_GRSLCT_SYMBOL_LINE_STYLE     1240
#define ID_GRUFUN_UNDO                  1240
#define ID_GRDEFAULTSYMBOL_SLIDER       1242
#define ID_GRDEFAULTSYMBOL_LOAD         1243
#define ID_GRDEFAULTSYMBOL_SAVE         1244
#define ID_GRDEFAULTSYMBOL_RESET        1245
#define ID_GRDEFAULTSYMBOL_Next         1246
#define ID_GRDEFAULTSYMBOL_CB_LINECONNECTION 1247
#define ID_GRDEFAULTSYMBOL_TYPE         1249
#define ID_GRDEFAULTSYMBOL_LINE_COLOR   1250
#define ID_GRDEFAULTSYMBOL_COLOR        1251
#define ID_GRDEFAULTSYMBOL_LINE_STYLE   1252
#define ID_GRDEFAULTSYMBOL_SIZE         1253
#define ID_GRDEFAULTSYMBOL_SIZE_SPIN    1254
#define ID_GRDEFAULTSYMBOL_SOLID        1255
#define ID_GRDEFAULTSYMBOL_LINE_THICKNESS 1256
#define ID_GRDEFAULTSYMBOL_LEGEND_SIZE  1257
#define ID_GRDEFAULTSYMBOL_LEGEND_SIZE_SPIN 1258
#define ID_GRDEFAULTSYMBOL_LEGEND_TEXT  1259
#define ID_GRPLOT_ADD                   1260
#define ID_GRDEFAULTSYMBOL_ADD          1260
#define ID_GRPLOT_DELETE                1261
#define ID_GRDEFAULTSYMBOL_DEL          1261
#define ID_GRPLOT_TOEMF                 1262
#define ID_GRDEFAULTSYMBOL_PREV         1262
#define ID_GRPLOTWIZARD_PATTERNFILE     1263
#define ID_GRPLOT_COPY                  1263
#define ID_GRPLOTWIZARD_READPATTERN     1264
#define ID_GRPLOTWIZARD_XSERIES01_COUNT 1269
#define ID_GRPLOTWIZARD_XSERIES02_COUNT 1271
#define ID_GRPLOTWIZARD_XSCATTER01_COUNT 1274
#define ID_GRPLOTWIZARD_XSCATTER02_COUNT 1275
#define ID_GRPLOTWIZARD_XSCATTER03_COUNT 1277
#define ID_GRPLOTWIZARD_SPLITFILE       1278
#define ID_GRPLOTWIZARD_READSPLIT       1279
#define ID_GRPLOTWIZARD_XSCATTER05_COUNT 1281
#define ID_GRPLOTWIZARD_XSCATTER06_COUNT 1283
#define ID_GRPLOTWIZARD_EXECSPLIT       1284
#define ID_GRPLOTWIZARD_EXECPATTERN     1285
#define ID_GRPLOTWIZARD_WRITESCRIPT     1286
#define ID_GRPLOTWIZARD_XSCATTER04_COUNT 1287
#define ID_GRPLOTWIZARD_XSCATTER07_COUNT 1289
#define ID_GRPLOTWIZARD_MAP01_COUNT     1291
#define ID_GRPLOTWIZARD_MAP01_READ      1292
#define ID_GRPLOTWIZARD_MAP01_CREATE    1294
#define ID_GRPLOTWIZARD_MAP02_COUNT     1295
#define ID_GRPLOTWIZARD_POSTPROCESSTYPE 1303
#define ID_GRPLOTWIZARD_MAP01_EDIT      1304
#define ID_GRPLOTWIZARD_MAP_COMPOSITE   1372
#define ID_PATHENV_SAMPLE               1374
#define ID_PATHENV_GARGAMEL             1375
#define ID_FONTD_HEIGHT_SPIN            1376
#define ID_PATHENV_SMURFETTE            1376
#define ID_PATHENV_EDITOR               1377
#define ID_PATHENV_GARGAMEL_BROWSER     1378
#define ID_PATHENV_SMURFETTE_BROWSER    1379
#define ID_GRVIEW_X1_SPIN               1380
#define ID_PATHENV_EDITOR_BROWSER       1380
#define ID_GRVIEW_Y1_SPIN               1381
#define ID_PATHENV_SAMPLE_BROWSER       1381
#define ID_GRVIEW_X2_SPIN               1382
#define ID_PATHENV_HOME                 1382
#define ID_GRVIEW_Y2_SPIN               1383
#define ID_PATHENV_HOME_DIRECTORY       1383
#define ID_GRAXIS_DISPLAY_ON            2000
#define ID_GRVIEW_INFLATE               2000
#define ID_GRAXIS_DISPLAY_OFF           2001
#define ID_GRVIEW_DEFLATE               3001
#define ID_GRVIEW_INFLATE_X             3002
#define ID_GRVIEW_INFLATE_Y             3003
#define ID_GRVIEW_DEFLATE_X             3004
#define ID_GRVIEW_DEFLATE_Y             3005
#define ID_GRVIEW_PRESET_11             3100
#define ID_GRVIEW_PRESET_121            3101
#define ID_GRVIEW_PRESET_122            3102
#define ID_GRVIEW_PRESET_131            3103
#define ID_GRVIEW_PRESET_132            3104
#define ID_GRVIEW_PRESET_133            3105
#define ID_GRVIEW_PRESET_141            3106
#define ID_GRVIEW_PRESET_142            3107
#define ID_GRVIEW_PRESET_143            3108
#define ID_GRVIEW_PRESET_144            3109
#define ID_GRVIEW_PRESET_161            3110
#define ID_GRVIEW_PRESET_162            3111
#define ID_GRVIEW_PRESET_163            3112
#define ID_GRVIEW_PRESET_164            3113
#define ID_GRVIEW_PRESET_165            3114
#define ID_GRVIEW_PRESET_166            3115
#define ID_GRVIEW_PRESET_181            3116
#define ID_GRVIEW_PRESET_182            3117
#define ID_GRVIEW_PRESET_183            3118
#define ID_GRVIEW_PRESET_184            3119
#define ID_GRVIEW_PRESET_185            3120
#define ID_GRVIEW_PRESET_186            3121
#define ID_GRVIEW_PRESET_187            3122
#define ID_GRVIEW_PRESET_188            3123
#define ID_GRXYZB_XLB_AUTO              3200
#define ID_GRXYZB_XUB_AUTO              3201
#define ID_GRXYZB_YLB_AUTO              3202
#define ID_GRXYZB_YUB_AUTO              3203
#define ID_GRXYZB_ZLB_AUTO              3204
#define ID_GRXYZB_ZUB_AUTO              3205
#define ID_GRXYZB_XLB_ALL               3206
#define ID_GRXYZB_XUB_ALL               3207
#define ID_GRXYZB_YLB_ALL               3208
#define ID_GRXYZB_YUB_ALL               3209
#define ID_GRXYZB_ZLB_ALL               3210
#define ID_GRXYZB_ZUB_ALL               3211
#define IDM_EXEC_GR                     32771
#define ID_FILE_SAVE_AS_                32772
#define ID_FILE_OPEN_                   32773
#define ID_FILE_NEW_                    32774
#define IDM_GR_MARKER                   32775
#define ID_FILE_SAVE_                   32776
#define ID_WINDOW_NEW_                  32777
#define IDM_CLOSEALL                    32779
#define IDM_CLOSE_ALL_WINDOWS           32780
#define IDM_GR_RENOVATOR                32781
#define IDM_GR_BATCHER                  32783
#define IDM_WINDOWSFONT                 32785
#define IDM_HOMEMADEFONT                32786
#define IDM_HISTORY                     32788
#define IDM_PREFERENCE                  32789
#define IDM_VIEW_SCRIPT                 32790
#define IDM_GR_MIXER                    32791
#define IDM_VIEW_LEFT                   32792
#define IDM_VIEW_RIGHT                  32793
#define IDM_VIEW_UP                     32794
#define IDM_VIEW_DOWN                   32795
#define IDM_GRPLOT_WIZARD_FROMDATA      32796
#define IDM_FIT_TO_OBJECT               32797
#define IDM_GRPLOT_WIZARD_THRUGARGAMEL  32798
#define IDM_FIT_TO_CANVAS               32799
#define IDM_VIEW_MAG_PAGE_WIDTH         32800
#define IDM_VIEW_MAG_PAGE_HEIGHT        32801
#define IDM_ABOUT_AUTHOR                32802
#define IDM_VIEW_MAG_ARBITRARY          32803
#define IDM_VIEW_WINDOW_FIT             32804
#define IDM_CLEAR                       32811
#define IDM_VIEW_TRANSLATE              32812
#define IDM_VIEW_DUMP2PS                32816
#define IDM_VIEW_DUMP2EMF               32817
#define IDM_VIEW_FULL                   32823
#define IDM_VIEW_ZOOM_OFF               32824
#define IDM_VIEW_ZOOM_IN                32825
#define IDM_VIEW_ZOOM_OUT               32826
#define IDM_VIEW_REDRAW                 32827
#define IDM_VIEW_HAND                   32832
#define IDM_VIEW_MAG_50                 32834
#define IDM_VIEW_MAG_25                 32835
#define IDM_VIEW_MAG_100                32836
#define IDM_VIEW_MAG_200                32837
#define IDM_VIEW_MAG_400                32838
#define IDM_VIEW_MAG_75                 32839
#define IDM_VIEW_MAG_125                32840
#define IDM_VIEW_CANVAS_A4H             32844
#define IDM_VIEW_CANVAS_A4V             32845
#define IDM_VIEW_CANVAS_ARBITRARY       32846
#define IDM_FILE_SAVEAS_WMF             32848
#define IDM_FILE_SAVEAS_EMF             32849
#define IDM_FILE_SAVEAS_PSF             32850
#define IDM_FILE_SAVEAS_HPGLF           32851
#define IDM_BRAINY                      32854
#define IDM_VIEW_LOG                    32855
#define IDM_GR_PLOT_VIEWPORT            32883
#define IDM_GR_PLOT_DEFAULTSYMBOL       32885
#define IDM_SMURFETTE                   32897
#define IDM_GARGAMEL                    32898
#define IDM_PALLETE                     32899
#define IDM_SAMPLE0                     32900
#define IDM_SAMPLE1                     32901
#define IDM_SAMPLE2                     32902
#define IDM_SAMPLE3                     32903
#define IDM_SAMPLE4                     32904
#define IDM_SAMPLE5                     32905
#define IDM_SAMPLE6                     32906
#define IDM_SAMPLE7                     32907
#define IDM_GR_PLOT_PAGE                32910
#define IDM_GR_ATTR_PAGE                32911
#define IDM_GR_DATA_PAGE                32912
#define IDM_GR_XYZB_PAGE                32913
#define IDM_GR_SYMB_PAGE                32914
#define IDM_GR_AXIS_PAGE                32915
#define IDM_GR_TEXT_PAGE                32916
#define IDM_GR_UFUN_PAGE                32917
#define IDM_GR_VIEW_PAGE                32918
#define IDM_GR_GLOB_PAGE                32919

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
