# -*- coding: utf-8 -*-
"""
Created on Sun Mar 26, 2016 - Apr 2

@author: Y. Kim

Command line options: setup.py build_ext --inplace

<http://www.swig.org/Doc1.3/Python.html>

In this example, the line: example_module = Extension(....) creates an
Extension module object, defining the name as _example, and using the source
code files: example_wrap.c, generated by swig, and example.c, your original c
source. The swig (and other python extension modules) tradition is for the
compiled extension to have the name of the python portion, prefixed by an
underscore. If the name of your python module is "example.py", then the name
of the corresponding object file will be"_example.so"
The setup call then sets up distutils to build your package, defining some
meta data, and passing in your extension module object. Once this is saved as
setup.py, you can build your extension with these commands:

   $ swig -python example.i
   $ python setup.py build_ext --inplace

And a .so, or .pyd or... will be created for you. It will build a version that
matches the python that you run the command with. Taking apart the command
line:

   . python -- the version of python you want to build for
   . setup.py -- the name of your setup script (it can be called anything, but
        setup.py is the tradition)
   . build_ext -- telling distutils to build extensions
   . --inplace -- this tells distutils to put the extension lib in the current
        dir. Otherwise, it will put it inside a build hierarchy, and you'd
        have to move it to use it.

The distutils have many other features, consult the python distutils docs for
details. This same approach works on all platforms if the appropriate compiler
is installed. (it can even build extensions to the standard Windows Python
using MingGW)

"""

from distutils.core import setup, Extension, os
import glob
import re

topDir = "."
sourceFiles = ['ynr_wrap.c']
includeDirs = ['yNumRecipe']
excludeDirs = ['.vs', 'Debug', 'build', 'ipch', 'myC', 'myCpp', 'x64',
               'Release', '__pycache__']

topDirPath = os.path.abspath(topDir)
for root, dirs, filenames in os.walk(topDirPath):
    # dirs[:] = [d for d in dirs if d not in includeDirs]
    dirs[:] = [d for d in dirs if d not in excludeDirs]
    for dir in dirs:
        absPath = os.path.join(root, dir)
        includeDirs.append(absPath)
        globStr = "%s/*.c" % absPath
        files = glob.glob(globStr)
        """
        for f in files:
            #f=re.replace(topDirPath,'',f)
            f=f.replace(topDirPath,"",1)
            print(f)
        files[:]=[f.replace(topDirPath,'') for f in files]
        """
        sourceFiles += files

print("includeDirs:")
print(includeDirs)
print("sourceFiles:")
print(sourceFiles)
# print(['-I"'+d+'"' for d in includeDirs])

# SWIG Options
swigOptions = ["-debug-tmsearch"]
swigOptions += ['-I"' + d + '"' for d in includeDirs],

# MS Visual Studio Community 2015 Compiler option, to turn off deprecation warnings.
extraArgs = ['/wd4996']

EM = Extension(
    '_yNumRecipe',
    sources=sourceFiles,
    include_dirs=includeDirs,
    # swig_opts = swigOptions,
    extra_compile_args=extraArgs

)

setup(
    name='yNumRecipe',
    version='0.1',
    author="Y Kim",
    description="Y Numerical Recipe of C and Cpp",
    ext_modules=[EM],
    py_modules=["yNumRecipe"]
)
