# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info

if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_yNumRecipe', [dirname(__file__)])
        except ImportError:
            import _yNumRecipe
            return _yNumRecipe
        if fp is not None:
            try:
                _mod = imp.load_module('_yNumRecipe', fp, pathname, description)
            finally:
                fp.close()
            return _mod


    _yNumRecipe = swig_import_helper()
    del swig_import_helper
else:
    import _yNumRecipe
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)


def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass


    _newclass = 0


def new_doublePointer():
    return _yNumRecipe.new_doublePointer()


new_doublePointer = _yNumRecipe.new_doublePointer


def copy_doublePointer(value):
    return _yNumRecipe.copy_doublePointer(value)


copy_doublePointer = _yNumRecipe.copy_doublePointer


def delete_doublePointer(obj):
    return _yNumRecipe.delete_doublePointer(obj)


delete_doublePointer = _yNumRecipe.delete_doublePointer


def doublePointer_assign(obj, value):
    return _yNumRecipe.doublePointer_assign(obj, value)


doublePointer_assign = _yNumRecipe.doublePointer_assign


def doublePointer_value(obj):
    return _yNumRecipe.doublePointer_value(obj)


doublePointer_value = _yNumRecipe.doublePointer_value


def new_doubleArray(nelements):
    return _yNumRecipe.new_doubleArray(nelements)


new_doubleArray = _yNumRecipe.new_doubleArray


def delete_doubleArray(ary):
    return _yNumRecipe.delete_doubleArray(ary)


delete_doubleArray = _yNumRecipe.delete_doubleArray


def doubleArray_getitem(ary, index):
    return _yNumRecipe.doubleArray_getitem(ary, index)


doubleArray_getitem = _yNumRecipe.doubleArray_getitem


def doubleArray_setitem(ary, index, value):
    return _yNumRecipe.doubleArray_setitem(ary, index, value)


doubleArray_setitem = _yNumRecipe.doubleArray_setitem


class UVNParameter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UVNParameter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UVNParameter, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mean"] = _yNumRecipe.UVNParameter_mean_set
    __swig_getmethods__["mean"] = _yNumRecipe.UVNParameter_mean_get
    if _newclass:
        mean = _swig_property(_yNumRecipe.UVNParameter_mean_get, _yNumRecipe.UVNParameter_mean_set)
    __swig_setmethods__["stdev"] = _yNumRecipe.UVNParameter_stdev_set
    __swig_getmethods__["stdev"] = _yNumRecipe.UVNParameter_stdev_get
    if _newclass:
        stdev = _swig_property(_yNumRecipe.UVNParameter_stdev_get, _yNumRecipe.UVNParameter_stdev_set)

    def __init__(self):
        this = _yNumRecipe.new_UVNParameter()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    __swig_destroy__ = _yNumRecipe.delete_UVNParameter
    __del__ = lambda self: None


UVNParameter_swigregister = _yNumRecipe.UVNParameter_swigregister
UVNParameter_swigregister(UVNParameter)


class BVNParameter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BVNParameter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BVNParameter, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_x"] = _yNumRecipe.BVNParameter_m_x_set
    __swig_getmethods__["m_x"] = _yNumRecipe.BVNParameter_m_x_get
    if _newclass:
        m_x = _swig_property(_yNumRecipe.BVNParameter_m_x_get, _yNumRecipe.BVNParameter_m_x_set)
    __swig_setmethods__["s_x"] = _yNumRecipe.BVNParameter_s_x_set
    __swig_getmethods__["s_x"] = _yNumRecipe.BVNParameter_s_x_get
    if _newclass:
        s_x = _swig_property(_yNumRecipe.BVNParameter_s_x_get, _yNumRecipe.BVNParameter_s_x_set)
    __swig_setmethods__["m_y"] = _yNumRecipe.BVNParameter_m_y_set
    __swig_getmethods__["m_y"] = _yNumRecipe.BVNParameter_m_y_get
    if _newclass:
        m_y = _swig_property(_yNumRecipe.BVNParameter_m_y_get, _yNumRecipe.BVNParameter_m_y_set)
    __swig_setmethods__["s_y"] = _yNumRecipe.BVNParameter_s_y_set
    __swig_getmethods__["s_y"] = _yNumRecipe.BVNParameter_s_y_get
    if _newclass:
        s_y = _swig_property(_yNumRecipe.BVNParameter_s_y_get, _yNumRecipe.BVNParameter_s_y_set)
    __swig_setmethods__["r"] = _yNumRecipe.BVNParameter_r_set
    __swig_getmethods__["r"] = _yNumRecipe.BVNParameter_r_get
    if _newclass:
        r = _swig_property(_yNumRecipe.BVNParameter_r_get, _yNumRecipe.BVNParameter_r_set)

    def __init__(self):
        this = _yNumRecipe.new_BVNParameter()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    __swig_destroy__ = _yNumRecipe.delete_BVNParameter
    __del__ = lambda self: None


BVNParameter_swigregister = _yNumRecipe.BVNParameter_swigregister
BVNParameter_swigregister(BVNParameter)

_yNumRecipe.yNr4_header_INSTALLED_swigconstant(_yNumRecipe)
yNr4_header_INSTALLED = _yNumRecipe.yNr4_header_INSTALLED


def yZscore1d(x, n):
    return _yNumRecipe.yZscore1d(x, n)


yZscore1d = _yNumRecipe.yZscore1d


def yZscore2d(x, y, n):
    return _yNumRecipe.yZscore2d(x, y, n)


yZscore2d = _yNumRecipe.yZscore2d


def yBVNCDFOCP(vXB0, vYB0, vSize, n, Area):
    return _yNumRecipe.yBVNCDFOCP(vXB0, vYB0, vSize, n, Area)


yBVNCDFOCP = _yNumRecipe.yBVNCDFOCP


def yBVSNCDFOCP(vXB0, vYB0, vSize, Area):
    return _yNumRecipe.yBVSNCDFOCP(vXB0, vYB0, vSize, Area)


yBVSNCDFOCP = _yNumRecipe.yBVSNCDFOCP


def demo_Fig_33_on_page_52():
    return _yNumRecipe.demo_Fig_33_on_page_52()


demo_Fig_33_on_page_52 = _yNumRecipe.demo_Fig_33_on_page_52


def demo_Fig_35_on_page_54():
    return _yNumRecipe.demo_Fig_35_on_page_54()


demo_Fig_35_on_page_54 = _yNumRecipe.demo_Fig_35_on_page_54


def demo_Fig_40_on_page_59():
    return _yNumRecipe.demo_Fig_40_on_page_59()


demo_Fig_40_on_page_59 = _yNumRecipe.demo_Fig_40_on_page_59


def demo_rectangle_9x9(set):
    return _yNumRecipe.demo_rectangle_9x9(set)


demo_rectangle_9x9 = _yNumRecipe.demo_rectangle_9x9
# This file is compatible with both classic and new-style classes.
