// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "GargamelSplitOcx.h"

/////////////////////////////////////////////////////////////////////////////
// CGargamelSplitOcx

IMPLEMENT_DYNCREATE(CGargamelSplitOcx, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGargamelSplitOcx properties

CString CGargamelSplitOcx::GetSplitScript()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CGargamelSplitOcx::SetSplitScript(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CGargamelSplitOcx operations

void CGargamelSplitOcx::NotifyFlagrantDialogOk()
{
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CGargamelSplitOcx::NotifyFlagrantDialogCancel()
{
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CGargamelSplitOcx::SetDirectory(LPCTSTR qPath)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 qPath);
}

void CGargamelSplitOcx::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
