// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gargamelpatternformatrixocx.h"

/////////////////////////////////////////////////////////////////////////////
// CGargamelPatternForMatrixOcx

IMPLEMENT_DYNCREATE(CGargamelPatternForMatrixOcx, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGargamelPatternForMatrixOcx properties

CString CGargamelPatternForMatrixOcx::GetPatternForMatrixScript()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CGargamelPatternForMatrixOcx::SetPatternForMatrixScript(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CGargamelPatternForMatrixOcx operations

void CGargamelPatternForMatrixOcx::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
