// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "GargamelSplitCtrl.h"

/////////////////////////////////////////////////////////////////////////////
// CGargamelSplitCtrl

IMPLEMENT_DYNCREATE(CGargamelSplitCtrl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGargamelSplitCtrl properties

CString CGargamelSplitCtrl::GetSplitScript()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CGargamelSplitCtrl::SetSplitScript(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CGargamelSplitCtrl operations

void CGargamelSplitCtrl::NotifyFlagrantDialogOk()
{
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CGargamelSplitCtrl::NotifyFlagrantDialogCancel()
{
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CGargamelSplitCtrl::SetDirectory(LPCTSTR qPath)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 qPath);
}

void CGargamelSplitCtrl::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
