//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GargamelPattern.rc
//
#define IDS_GARGAMELPATTERN             1
#define IDD_ABOUTBOX_GARGAMELPATTERN    1
#define IDB_GARGAMELPATTERN             1
#define IDI_ABOUTDLL                    1
#define IDS_GARGAMELPATTERN_PPG         2
#define ID_GARGAMEL_PATTERNWIZARD_OPENFILE 3
#define ID_WIZARD_OPENFILE              3
#define ID_GARGAMEL_PATTERNWIZARD_REOPEN 4
#define ID_WIZARD_REOPEN                4
#define IDD_GARGAMEL_PATTERN_WIZARD     132
#define IDD_GARGAMEL_PATTERN_SUPERSEDING 133
#define IDS_GARGAMELPATTERN_PPG_CAPTION 200
#define IDD_PROPPAGE_GARGAMELPATTERN    200
#define ID_FINDWHAT_IN_PATTERN          201
#define IDD_PROPPAGE_GARGAMELPATTRN2    201
#define ID_FINDWHAT_IN_ALIAS            202
#define ID_PATTRN2_BLOCK_SELECTION_ALL  202
#define ID_FINDWHAT_IN_LASTNO           203
#define ID_PATTRN2_CHECK                203
#define ID_FINDWHAT_IN_1STNO            204
#define ID_PATTRN2_ADD_WIZARD           204
#define ID_FINDWHAT_IN_EQUATION         205
#define ID_PATTRN2_SCRIPT_READ_ATTACH   205
#define ID_FINDWHAT_IN_FORMAT           206
#define ID_PATTRN2_BEGINNING_TEXT       206
#define ID_FINDWHAT_IN_UC               207
#define ID_PATTRN2_ENDING_TEXT          207
#define ID_FINDWHAT_IN_LC               208
#define ID_PATTRN2_1ST_COLUMN           208
#define ID_PATTRN2_FORMAT               209
#define ID_PATTRN2_FORMAT_HELP          210
#define ID_PATTRN2_EQUATION             211
#define ID_PATTRN2_CUTLOW               212
#define ID_GARGAMEL_PATTERNWIZARD_LISTBOX 1005
#define ID_WIZARD_LISTBOX               1005
#define ID_GARGAMEL_PATTERNWIZARD_SPECIALCHAR_OHTERS_STRING 1006
#define ID_WIZARD_SPECIALCHAR_OHTERS_STRING 1006
#define ID_GARGAMEL_PATTERNWIZARD_FIXEDWIDTH 1007
#define ID_WIZARD_FIXEDWIDTH            1007
#define ID_GARGAMEL_PATTERNWIZARD_SPECIALCHAR_SPACE 1009
#define ID_WIZARD_SPECIALCHAR_SPACE     1009
#define ID_GARGAMEL_PATTERNWIZARD_SPECIALCHAR_TAB 1010
#define ID_WIZARD_SPECIALCHAR_TAB       1010
#define ID_GARGAMEL_PATTERNWIZARD_SPECIALCHAR_OTHERS 1011
#define ID_WIZARD_SPECIALCHAR_OTHERS    1011
#define ID_GARGAMEL_PATTERNWIZARD_SPECIALCHAR 1012
#define ID_WIZARD_SPECIALCHAR           1012
#define ID_GARGAMEL_PATTERNWIZARD_FIXEDWIDTHNO 1015
#define ID_WIZARD_FIXEDWIDTHNO          1015
#define ID_GARGAMEL_PATTERNWIZARD_LINESCOPE 1016
#define ID_WIZARD_LINESCOPE             1016
#define ID_GARGAMEL_PATTERNWIZARD_FIXEDWIDTHNO_SPIN 1017
#define ID_WIZARD_FIXEDWIDTHNO_SPIN     1017
#define ID_GARGAMEL_PATTERNWIZARD_LINESCOPE_SPIN 1018
#define ID_WIZARD_LINESCOPE_SPIN        1018
#define ID_PATTERN_LISTCTRL             1019
#define ID_GARGAMEL_PATTERNWIZARD_FILTER 1019
#define ID_WIZARD_FILTER                1019
#define ID_PATTERN_ALIAS_METHOD         1022
#define ID_PATTERN_ATTRIBUTE            1023
#define ID_FINDWHAT                     1026
#define ID_REPLACEWITH                  1027
#define ID_PATTERN_TEXT                 1042
#define ID_PATTERN_GRAB_FIRST_NO        1043
#define ID_PATTERN_GRAB_LAST_NO         1044
#define ID_PATTERN_FORMAT               1045
#define ID_PATTERN_ALIAS                1046
#define ID_PATTERN_ADD                  1047
#define ID_PATTERN_ADD_WIZARD           1048
#define ID_PATTERN_INS                  1049
#define ID_PATTERN_DEL                  1050
#define ID_PATTERN_CLEAR                1051
#define ID_PATTERN_MOVEUP               1052
#define ID_PATTERN_EQUATION             1053
#define ID_PATTERN_ALIAS_NO_FROM        1054
#define ID_PATTERN_ALIAS_NO_TO          1055
#define ID_PATTERN_ALIAS_AUTO_TRY       1056
#define ID_PATTERN_CUTLOW               1057
#define ID_PATTERN_CUTHIGH              1058
#define ID_PATTERN_FORMAT_HELP          1059
#define ID_FORMAT_HELP                  1059
#define ID_PATTRN2_OTHER_COLUMNS        1060
#define ID_PATTRN2_BLOCK_SELECTION      1061
#define ID_PATTRN2_CUTHIGH              1062
#define ID_PATTERN_MOVEDOWN             1063
#define ID_PATTERN_ALIAS_AUTO_TB        1064
#define ID_PATTERN_SUPERSEDING          1065
#define ID_PATTERN_ALIAS_CHANGE         1066
#define ID_PATTERN_SCRIPT_READ_ATTACH   1067

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         215
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
