# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info

if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_yDrillSWIG', [dirname(__file__)])
        except ImportError:
            import _yDrillSWIG
            return _yDrillSWIG
        if fp is not None:
            try:
                _mod = imp.load_module('_yDrillSWIG', fp, pathname, description)
            finally:
                fp.close()
            return _mod


    _yDrillSWIG = swig_import_helper()
    del swig_import_helper
else:
    import _yDrillSWIG
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)


def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass


    _newclass = 0


def new_intPointer():
    return _yDrillSWIG.new_intPointer()


new_intPointer = _yDrillSWIG.new_intPointer


def copy_intPointer(value):
    return _yDrillSWIG.copy_intPointer(value)


copy_intPointer = _yDrillSWIG.copy_intPointer


def delete_intPointer(obj):
    return _yDrillSWIG.delete_intPointer(obj)


delete_intPointer = _yDrillSWIG.delete_intPointer


def intPointer_assign(obj, value):
    return _yDrillSWIG.intPointer_assign(obj, value)


intPointer_assign = _yDrillSWIG.intPointer_assign


def intPointer_value(obj):
    return _yDrillSWIG.intPointer_value(obj)


intPointer_value = _yDrillSWIG.intPointer_value


def new_intArray(nelements):
    return _yDrillSWIG.new_intArray(nelements)


new_intArray = _yDrillSWIG.new_intArray


def delete_intArray(ary):
    return _yDrillSWIG.delete_intArray(ary)


delete_intArray = _yDrillSWIG.delete_intArray


def intArray_getitem(ary, index):
    return _yDrillSWIG.intArray_getitem(ary, index)


intArray_getitem = _yDrillSWIG.intArray_getitem


def intArray_setitem(ary, index, value):
    return _yDrillSWIG.intArray_setitem(ary, index, value)


intArray_setitem = _yDrillSWIG.intArray_setitem


def check_array1d(arrayb0, narray, result):
    return _yDrillSWIG.check_array1d(arrayb0, narray, result)


check_array1d = _yDrillSWIG.check_array1d


def check_array2d_w_numpy(array2d):
    return _yDrillSWIG.check_array2d_w_numpy(array2d)


check_array2d_w_numpy = _yDrillSWIG.check_array2d_w_numpy
# This file is compatible with both classic and new-style classes.
